export enum ErrorMessages {
    INTERNAL_SERVER_ERROR = 'Internal server error',
    NOT_FOUND = 'Resource not found',
    VALIDATION_ERROR = 'Validation failed',
    UNAUTHORIZED = 'Unauthorized access',
    FORBIDDEN = 'Access forbidden',
    CONFLICT = 'Resource already exists',
    BAD_REQUEST = 'Bad request',
    INVALID_ID = 'Invalid ID format',

    DB_CONNECTION_ERROR = 'Database connection error',
    DB_QUERY_ERROR = 'Database query error',
    DB_DUPLICATE_ERROR = 'Duplicate entry found',
    DB_VALIDATION_ERROR = 'Database validation error',

    INVALID_CREDENTIALS = 'Invalid credentials',
    TOKEN_EXPIRED = 'Token has expired',
    TOKEN_INVALID = 'Invalid token',
    TOKEN_REQUIRED = 'Authentication token is required',

    USER_NOT_FOUND = 'User not found',
    USER_ALREADY_EXISTS = 'User already exists',
    USER_INVALID_CREDENTIALS = 'Invalid user credentials',

    PRODUCT_NOT_FOUND = 'Product not found',
    FAILED_PRODUCT_BLOCK = 'Failed to block product',
    PRODUCT_IS_BLOCKED = 'Product is blocked',
    PRODUCT_ALREADY_EXISTS = 'A product with this name already exists.',
    PRODUCT_DUPLICATE_NAME = 'Another product with this name already exists under this vendor.',
    PRODUCT_IMAGES_REQUIRED = 'At least 3 images are required.',
    PRODUCT_VARIANT_REQUIRED = 'At least one variant is required.',
    PRODUCT_VARIANT_TYPE_REQUIRED = 'Variant type is required.',
    PRODUCT_DUPLICATE_VARIANT_TYPE = 'Duplicate variant type "{type}" found. Variant types must be unique.',
    PRODUCT_VARIANT_VALUE_REQUIRED = 'Value for variant "{type}" is required.',
    PRODUCT_DUPLICATE_VARIANT_VALUE = 'Duplicate value "{value}" found in variant "{type}". Values must be unique within each variant type.',
    PRODUCT_VARIANT_VALUE_PRICE_INVALID = 'Price for value "{value}" in variant "{type}" must be a non-negative number.',
    PRODUCT_VARIANT_VALUE_STOCK_INVALID = 'Stock for value "{value}" in variant "{type}" must be a non-negative number.',
    PRODUCT_INVALID_VARIANT_DATA = 'Invalid variant data: type and at least one value are required.',
    PRODUCT_ALREADY_BLOCKED = 'Product is already blocked.',
    PRODUCT_NOT_ENOUGH_STOCK = 'Not enough stock available',
    PRODUCT_STOCK_BELOW_MIN = 'Stock would fall below the minimum limit',
    PRODUCT_STOCK_ABOVE_MAX = `You can't add more than {max} units per order`,

    CATEGORY_NOT_FOUND = "Category not found.",
    CATEGORY_ALREADY_EXISTS = "Category with this name already exists.",
    CATEGORY_NAME_REQUIRED = "Category name is required and must be a string.",
    CATEGORY_NAME_MIN_LENGTH = "Category name must be at least 3 characters long.",
    CATEGORY_ID_REQUIRED = "Category ID is required.",
    CATEGORY_NAME_EMPTY = "Name can't be empty.",
    CATEGORY_BLOCKED_ALREADY = "Category is already blocked.",
    CATEGORY_NOT_BLOCKED = "Category is not blocked.",
    CATEGORY_FAILED_TO_BLOCK = "Failed to block category.",
    CATEGORY_FAILED_TO_UNBLOCK = "Failed to unblock category.",
    CATEGORY_FAILED_TO_UPDATE = "Failed to update category.",
    CATEGORY_FAILED_TO_REMOVE_SUBCATEGORY = "Failed to remove subcategory.",
    CATEGORY_FAILED_TO_ADD_SUBCATEGORY = "Failed to add subcategory.",
    CATEGORY_CANNOT_BE_OWN_SUBCATEGORY = "A category cannot be its own subcategory.",
    CATEGORY_SUBCATEGORY_NOT_INCLUDED = "SubCategory is not part of this category.",
    CATEGORY_ID_AND_SUBCATEGORY_ID_REQUIRED = "Both Category ID and SubCategory ID are required.",
    CATEGORY_FAILED_TO_FETCH = "Failed to fetch category.",

    VENDOR_NOT_FOUND = 'Vendor not found',
    VENDOR_ALREADY_EXISTS = 'Vendor already exists',
    VENDOR_INVALID_DETAILS = 'Invalid vendor details',
    VENDOR_UPDATE_FAILED = 'Vendor update failed',

    ORDER_NOT_FOUND = 'Order not found',
    ORDER_ALREADY_COMPLETED = 'Order has already been completed',
    ORDER_INVALID_STATUS = 'Invalid order status',
    ORDER_PAYMENT_FAILED = 'Order payment failed',
    ORDER_UPDATE_FAILED = 'Failed to update the order',

    CART_NOT_FOUND = 'Cart not found',
    CART_ITEM_NOT_FOUND = 'Cart item not found',
    CART_EMPTY = 'Cart is empty',
    CART_ITEM_QUANTITY_INVALID = 'Invalid item quantity in cart',
    CART_UPDATE_FAILED = 'Failed to update cart',

    OFFER_NOT_FOUND = 'Offer not found',
    OFFER_ALREADY_EXISTS = "Offer already exists with category",
    OFFER_UPDATE_FAILED = "Failed to update offer",
    OFFER_START_DATE_AFTER_END_DATE = 'Start date cannot be after end date.',
    OFFER_DISCOUNT_OUT_OF_RANGE = 'Discount should be between 100 and 1000',
    OFFER_DISCOUNT_EXCEEDS_ORIGINAL_PRICE = 'Discount should be less than the original price',
    OFFER__FAILED_TO_GET = "Fail to get offers",
    CATEGORY_NAME_TOO_SHORT = "Category name should be required 3 characters",
    CATEGORY_NAME_INVALID = "Category name invalid",
    PAYMENT_INVALID_AMOUNT = "Invalid or missing amount",
    PAYMENT_MAX_LIMIT_EXCEEDS = "Amount exceeds Razorpay's maximum limit (₹5,00,000)",
    PAYMENT_ORDER_ID_CREATE_FAILED = "Failed to create payment order id",
    PAYMENT_MIN_LIMIT_EXCEEDS = `Please enter a minimum amount of ₹50`
}
