export enum OtpType {
    SIGNUP = "SIGNUP",
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    VENDOR_APPROVED = "VENDOR_APPROVED",
    VENDOR_REJECTED = "VENDOR_REJECTED",
    PRODUCT_APPROVED = "PRODUCT_APPROVED",
    PRODUCT_REJECTED = "PRODUCT_REJECTED",
    CHANGE_EMAIL = "CHANGE_EMAIL"
}

export enum RoleType {
    VENDOR = "vendor",
    USER = "user"
}
